[package]
name = "egui_typed_input"
version = "0.1.0"
edition = "2024"
# based on work from BfBB-Clash

[dependencies]
egui = { version = "0.31", default-features = false }

[dev-dependencies]
eframe = "0.31"
